### ISSUE TITLE
Saves new water component if I exit withtout saving

### ISSUE THREAD

**Issue by Dgzt** [jpooleycodes/Mundus#27]
If I add new water component to the project and exit without saving the application saves the new water component.

I've tried that delete water component and exit without save and if open the application the water component is still there, so the delete function is working correctly.

I've checked the source code and I've seen there is saving when I add new terrain.

Should we save the project if we add new water or terrain component to the project?

**Comment by jpooleycodes** [comment]
Good point. If we dont save on water creation, what should happen to the asset files and meta files that get created for the water when you close the app? Leave them?

**Comment by Dgzt** [comment]
Good question. We could store the created file paths in memory cache and remove it when close the app. What do you think?

**Comment by jpooleycodes** [comment]
That sounds doable, it will need to be able to remove the files, and also the gameoject from the scene graph as well. I may try to add this as a Github project to see how the projects system works
