### ISSUE TITLE
Setup gdx-runtime for a package repository

### ISSUE THREAD

**Issue by Dgzt** [jpooleycodes/Mundus#31]
Currently if we want to use the gdx-runtime then we should put the compiled jar into the project instead of to use a package repository. I think this is a bit uncomfortable. 

So I think before the next release we should setup the gdx-runime that someone could use it via package repository, e.g. JitPack.

**Comment by jpooleycodes** [comment]
I agree, would like to have the runtime working a little better first. I am working on skybox now but maybe can work on runtime after to get it caught up.
